### PR TITLE
WIP: Fixes team selection panel and the resulting clan tag bug

### PR DESCRIPTION
**Pull request by Nobody-x**
As described in #245 I was facing this problem and tried to fix it.

Seems like in CS:GO when we block player_team event it prevent the team selection screen to close directly and we need to click a second time or to press Esc to hide it.

The side effect was to break the team tag feature but I found a workaround for that.

For the moment this fix is in test on my own community server.

### CODE REVIEW

**Comment by Nobody-x** [comment]
@splewis can you convert this PR to draft please ?

**Comment by splewis** [comment]
Done.

**Comment by melkor217** [comment]
I've just tested your change with `SourceMod Version: 1.10.0.6460`. Team selection panel works just fine, but clang tag "Arena N" sometimes disappear for players.

**Comment by Nobody-x** [comment]
> I've just tested your change with `SourceMod Version: 1.10.0.6460`. Team selection panel works just fine, but clang tag "Arena N" sometimes disappear for players.

Yes I'm still working on it. When this solution fixed the clan tag problem in a local server, when I tested it on my community server the problem remains. I this is due to the player_team event and some engine timing I think (when a player join a team, the game code initialise some things and reset his clan tag after a short time).

Yesterday I tested another solution (Silent without blocking player_team event when player use the select menu but block it when the plugin change the player team) but unfortunately it didn't work 100% either. When a player manually join spec then go back in game again, he still have the selection menu bug.

I'm still testing some other ideas right now.

**Comment by Nobody-x** [comment]
Hi there, some news.

I tried a lot of things but I didn't manage to fix all the related issues of this pull request.

While the team selection menu bug is the result of blocking player_team event, removing this logic introduce new bugs. The main bug is the clan tag that reflects the current player's arena which is override by the game with the player's clan tag.

When I tried to create small plugin with almost the same logic to assign clantag to a player, this worked perfectly. The only things I never tested is to reproduce the queuing system, and I think it can come from there. Maybe something with switching players into another (or the same) team without killing them.

This need more investigating  and testing but I don't have more time to do it since I don't have an am server anymore to test on.

**Comment by crashzk** [comment]
@Nobody-x if you want to proceed with these changes i would be happy to test on my server to see if everything goes well.

**Comment by crashzk** [comment]
I believe you can refuse this PR and use https://github.com/splewis/csgo-multi-1v1/pull/283

**Pull request closed without merging**
