### PR TITLE
Add R8 Revolver

### PR DESCRIPTION
**Pull request by earlcochran**
Added the new revolver to the config

### CODE REVIEW

**Comment by splewis** [comment]
Considering this lets people use them on *pistol rounds*, which are really intended to simulate actual pistol rounds with $800, I don't think it makes sense to add this weapon here.

Of course, users can always add it to this file themselves (just like with the scout as a rifle...ugh...)

It definitely makes a good custom round though, i.e. https://forums.alliedmods.net/showpost.php?p=2370580&postcount=928

**Comment by latematt** [comment]
@splewis if it's supposed to "simulate actual pistol rounds with $800" then why do you allow people who use guns other than the default pistols (glock, usps, p2k, etc) to have body armor? you can't have body armor if you buy other pistols such as the p250 or 57.

**Comment by splewis** [comment]
They don't have kevlar.

https://github.com/splewis/csgo-multi-1v1/blob/master/scripting/multi1v1/roundtypes.sp#L132

**Comment by latematt** [comment]
Damn, my bad! I guess the server I tested it on was on a custom version (unless this was added recently)
Sorry!

On 12/11/2015 7:48 PM, Sean Lewis wrote:

They don't have kevlar.

https://github.com/splewis/csgo-multi-1v1/blob/master/scripting/multi1v1/roundtypes.sp#L132

**Pull request closed without merging**
